# Generated by Django 2.2.13 on 2020-06-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200628_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
