# Generated by Django 2.2.13 on 2020-06-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200628_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cv',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
