# Generated by Django 2.2.13 on 2020-06-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200628_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
