# Generated by Django 2.2.13 on 2020-07-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200628_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='personal_profile',
            field=models.TextField(default=''),
        ),
    ]
