# Generated by Django 2.2.13 on 2020-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_education_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(default='', max_length=400),
        ),
    ]
