# Generated by Django 2.2.13 on 2020-07-06 14:07

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_cv_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=[], max_length=1010, size=10),
        ),
    ]
